/***************************************************************
    *  DO NOT EDIT THIS FILE!
    *         
    *  This file is automatically generated by HP Service Test.
    *  Manually changing the contents of this file may result in 
    *  loss of information.
    *          
    *  To edit the test, open the file ‘APITest1.st’ 
    *  in HP Service Test.
     ***************************************************************/
    
    namespace Script
    {
    using System;
    using System.Text;
    using System.Threading;
    using System.Xml;
    using System.Xml.Schema;
    using HP.ST.Fwk.ReporterFWK;
    using HP.ST.Shared.Utilities;
    using HP.ST.Ext.BindingImpl.Getters;
    using HP.ST.Ext.BindingImpl.Setters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.PropInfo;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Getters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Setters;
    using HP.ST.Fwk.RunTimeFWK;
    using HP.ST.Fwk.RunTimeFWK.Utilities;
    using HP.ST.Fwk.RunTimeFWK.HelperClasses;
    using HP.ST.Fwk.RunTimeFWK.CompositeActivities;
    using HP.ST.Ext.BindingImpl.Setters.DataSourceSetters;
    using HP.ST.Fwk.JVMLoader;
    using System.IO;
    using System.Collections.Generic;
    using System.Reflection;
    using HP.ST.Fwk.SOAReplayAPI;
    using HP.ST.Fwk.UFTLicensing;
    
    
    
    public partial class WorkFlowScript : STWorkFlowScriptBase
    {    
    	TestUserCode _userCode = null;
    	TestEntities _flow = null;
    	static Reporter reporter;
    	int reportLevelInTree;
        HP.ST.Fwk.ReportCreator.QTPEngine.QTPEngineReportCreator reportCreator;
    	
    	public BindDirection bind_dir43 = null;
        public BindDirection bind_dir44 = null;
        public BindDirection bind_dir45 = null;
        public BindDirection bind_dir46 = null;
        public BindDirection bind_dir47 = null;
        public BindDirection bind_dir48 = null;
        public HP.ST.Ext.BasicActivities.DataCursorActivity DataCursorActivity25 = null;
        public BindDirection bind_dir49 = null;
        public HP.ST.Fwk.SOAReplayAPI.DataHandling.CursorMovementPolicy DataCursorActivity25_Policy = null;
        public BindDirection bind_dir50 = null;
        public BindDirection bind_dir51 = null;
        public BindDirection bind_dir52 = null;
        public BindDirection bind_dir53 = null;
        
        public IEnumerable<FeaturesGroup> LicensedFeatures
        {
        
        get
        {
        List<FeaturesGroup> features = new List<FeaturesGroup>();
        return features;
        
        }
        
        }
        
        public WorkFlowScript()
            : base(VuserClass.CommandLineArguments, new STRunTimeContext(), "test")
        {	
        	UpdateContextWithActionFolder(String.Empty);
        	
        }
        
        public WorkFlowScript(ISTRunTimeContext ctx)
            : base(VuserClass.CommandLineArguments, ctx, "test")
            
        {
        	this._context = ctx;
        	UpdateContextWithActionFolder(String.Empty);
        	UpdateTestSettings(ctx);
        }
        
        internal void InitializeComponent()
        {
        	LoadInput();
        	
        	InitReport();
        	
        	InitializeEncryptionManagerValues();
        
        	_userCode = new TestUserCode();
            _flow = _userCode;
            _flow.Context=this._context;
            
            
        
        	_flow.DataFetchActivity21 = new HP.ST.Ext.BasicActivities.DataFetchActivity(_context,"DataFetchActivity21");
            _flow.DataFetchActivity18 = new HP.ST.Ext.BasicActivities.DataFetchActivity(_context,"DataFetchActivity18");
            _flow.DataFetchActivity15 = new HP.ST.Ext.BasicActivities.DataFetchActivity(_context,"DataFetchActivity15");
            _flow.StartActivity1 = new HP.ST.Ext.BasicActivities.StartActivity(_context,"StartActivity1");
            _flow.Loop2 = new HP.ST.Fwk.RunTimeFWK.CompositeActivities.Loop<Loop2Input>(_context,"Loop2",LoopType.For);
            _flow.DataExporterActivity17 = new HP.ST.Ext.BasicActivities.DataExporterActivity(_context,"DataExporterActivity17");
            _flow.DataExporterActivity20 = new HP.ST.Ext.BasicActivities.DataExporterActivity(_context,"DataExporterActivity20");
            _flow.DataExporterActivity23 = new HP.ST.Ext.BasicActivities.DataExporterActivity(_context,"DataExporterActivity23");
            _flow.DataExporterCloseActivity24 = new HP.ST.Ext.BasicActivities.DataExporterCloseActivity(_context,"DataExporterCloseActivity24");
            _flow.EndActivity3 = new HP.ST.Ext.BasicActivities.EndActivity(_context,"EndActivity3");
            _flow.DataDisconnectActivity16 = new HP.ST.Ext.BasicActivities.DataDisconnectActivity(_context,"DataDisconnectActivity16");
            _flow.DataDisconnectActivity19 = new HP.ST.Ext.BasicActivities.DataDisconnectActivity(_context,"DataDisconnectActivity19");
            _flow.DataDisconnectActivity22 = new HP.ST.Ext.BasicActivities.DataDisconnectActivity(_context,"DataDisconnectActivity22");
            this.DataCursorActivity25 = new HP.ST.Ext.BasicActivities.DataCursorActivity(_context,"DataCursorActivity25");
            this.DataCursorActivity25_Policy = new HP.ST.Fwk.SOAReplayAPI.DataHandling.CursorMovementPolicy();
            _flow.Sequence14 = new HP.ST.Fwk.RunTimeFWK.CompositeActivities.Sequence(_context,"Sequence14");
            _flow.StServiceCallActivity11 = new HP.ST.Ext.WebServicesActivities.StServiceCallActivity(_context,"StServiceCallActivity11");
            _flow.StServiceCallActivity13 = new HP.ST.Ext.WebServicesActivities.StServiceCallActivity(_context,"StServiceCallActivity13");
            _flow.DataFetchActivity21.Comment = @"";
            _flow.DataFetchActivity21.IconPath = @"";
            _flow.DataFetchActivity21.AssemblyPath = @"AddIns\ServiceTest\BaseDataProviders\HP.ST.Ext.CustomDataProviders.dll";
            _flow.DataFetchActivity21.QueryClassName = @"HP.ST.Ext.CustomDataProviders.ExcelFileDataQuery";
            XmlDocument DataFetchActivity21_QueryParameters_Document = new XmlDocument();
            DataFetchActivity21_QueryParameters_Document.PreserveWhitespace = true;
            string xmlDataFetchActivity21Params = @"<Arguments><QueryParametersContainer><QueryParameter><Name>Id</Name><Value>1e535f23-7e8d-4262-81d9-126ab0ca3384</Value></QueryParameter><QueryParameter><Name>QueryName</Name><Value>flight_pairing!Sheet3</Value></QueryParameter><QueryParameter><Name>IsEmbedded</Name><Value>False</Value></QueryParameter><QueryParameter><Name>Externalized</Name><Value>False</Value></QueryParameter><QueryParameter><Name>GroupText</Name><Value>flight_pairing</Value></QueryParameter><QueryParameter><Name>FilePath</Name><Value>" + _context.ResourceManager.GetValue("{flight_pairing!Sheet3.TablePath}") + "</Value></QueryParameter><QueryParameter><Name>SheetName</Name><Value>Sheet3$</Value></QueryParameter><QueryParameter><Name>ContainsHeadersRow</Name><Value>True</Value></QueryParameter></QueryParametersContainer></Arguments>";
            DataFetchActivity21_QueryParameters_Document.LoadXml(xmlDataFetchActivity21Params);
            _flow.DataFetchActivity21.QueryParameters = DataFetchActivity21_QueryParameters_Document;
            _flow.dataSourceNameToDataSource.Add("flight_pairing!Sheet3", _flow.DataFetchActivity21);
            this.Activities.Add (_flow.DataFetchActivity21);
            _flow.DataFetchActivity18.Comment = @"";
            _flow.DataFetchActivity18.IconPath = @"";
            _flow.DataFetchActivity18.AssemblyPath = @"AddIns\ServiceTest\BaseDataProviders\HP.ST.Ext.CustomDataProviders.dll";
            _flow.DataFetchActivity18.QueryClassName = @"HP.ST.Ext.CustomDataProviders.ExcelFileDataQuery";
            XmlDocument DataFetchActivity18_QueryParameters_Document = new XmlDocument();
            DataFetchActivity18_QueryParameters_Document.PreserveWhitespace = true;
            string xmlDataFetchActivity18Params = @"<Arguments><QueryParametersContainer><QueryParameter><Name>Id</Name><Value>dd8b9eff-f23e-4d3e-97f0-69125736bdf4</Value></QueryParameter><QueryParameter><Name>QueryName</Name><Value>flight_pairing!Output</Value></QueryParameter><QueryParameter><Name>IsEmbedded</Name><Value>False</Value></QueryParameter><QueryParameter><Name>Externalized</Name><Value>False</Value></QueryParameter><QueryParameter><Name>GroupText</Name><Value>flight_pairing</Value></QueryParameter><QueryParameter><Name>FilePath</Name><Value>" + _context.ResourceManager.GetValue("{flight_pairing!Output.TablePath}") + "</Value></QueryParameter><QueryParameter><Name>SheetName</Name><Value>Output$</Value></QueryParameter><QueryParameter><Name>ContainsHeadersRow</Name><Value>True</Value></QueryParameter></QueryParametersContainer></Arguments>";
            DataFetchActivity18_QueryParameters_Document.LoadXml(xmlDataFetchActivity18Params);
            _flow.DataFetchActivity18.QueryParameters = DataFetchActivity18_QueryParameters_Document;
            _flow.dataSourceNameToDataSource.Add("flight_pairing!Output", _flow.DataFetchActivity18);
            this.Activities.Add (_flow.DataFetchActivity18);
            _flow.DataFetchActivity15.Comment = @"";
            _flow.DataFetchActivity15.IconPath = @"";
            _flow.DataFetchActivity15.AssemblyPath = @"AddIns\ServiceTest\BaseDataProviders\HP.ST.Ext.CustomDataProviders.dll";
            _flow.DataFetchActivity15.QueryClassName = @"HP.ST.Ext.CustomDataProviders.ExcelFileDataQuery";
            XmlDocument DataFetchActivity15_QueryParameters_Document = new XmlDocument();
            DataFetchActivity15_QueryParameters_Document.PreserveWhitespace = true;
            string xmlDataFetchActivity15Params = @"<Arguments><QueryParametersContainer><QueryParameter><Name>Id</Name><Value>b34bb4f0-e58d-4b76-96a3-913708c5e878</Value></QueryParameter><QueryParameter><Name>QueryName</Name><Value>flight_pairing!Input</Value></QueryParameter><QueryParameter><Name>IsEmbedded</Name><Value>False</Value></QueryParameter><QueryParameter><Name>Externalized</Name><Value>False</Value></QueryParameter><QueryParameter><Name>GroupText</Name><Value>flight_pairing</Value></QueryParameter><QueryParameter><Name>FilePath</Name><Value>" + _context.ResourceManager.GetValue("{flight_pairing!Input.TablePath}") + "</Value></QueryParameter><QueryParameter><Name>SheetName</Name><Value>Input$</Value></QueryParameter><QueryParameter><Name>ContainsHeadersRow</Name><Value>True</Value></QueryParameter></QueryParametersContainer></Arguments>";
            DataFetchActivity15_QueryParameters_Document.LoadXml(xmlDataFetchActivity15Params);
            _flow.DataFetchActivity15.QueryParameters = DataFetchActivity15_QueryParameters_Document;
            _flow.dataSourceNameToDataSource.Add("flight_pairing!Input", _flow.DataFetchActivity15);
            this.Activities.Add (_flow.DataFetchActivity15);
            _flow.StartActivity1.Comment = @"";
            _flow.StartActivity1.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_code_activity.png";
            _flow.StartActivity1.Name = @"Start";
            _flow.StartActivity1.JVM = new HP.ST.Ext.BasicActivities.JVMProperties();
            _flow.StartActivity1.IsJavaUsed = false;
            _flow.StartActivity1.JVM.Classpath = @"%CLASSPATH%";
            _flow.StartActivity1.JVM.AdditionalVMParameters = @"";
            _flow.StartActivity1.JMS = new HP.ST.Ext.BasicActivities.JMSProperties();
            _flow.StartActivity1.IsJmsUsed = false;
            _flow.StartActivity1.JMS.JNDIContextFactory = @"<Select...>";
            _flow.StartActivity1.JMS.JNDIProviderUrl = @"";
            _flow.StartActivity1.JMS.JMSConnectionFactory = @"";
            _flow.StartActivity1.JMS.SecurityPrincipal = @"";
            _flow.StartActivity1.JMS.SecurityCredentials = @"";
            _flow.StartActivity1.JMS.ConnectionsPerProcess = @"1";
            _flow.StartActivity1.JMS.TimeoutOptions = @"DN_User_defined_Timeout";
            _flow.StartActivity1.JMS.UserTimeout = @"20";
            _flow.StartActivity1.JMS.GenerateAutoSelector = @"No";
            this.Activities.Add (_flow.StartActivity1);
            _flow.Loop2.ConditionAsString = @"Run for 4 iterations";
            _flow.Loop2.NumberOfIterations = (int)4;
            _flow.Loop2.Comment = @"";
            _flow.Loop2.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_loop.png";
            _flow.Loop2.Name = @"Test Flow";
            _flow.Loop2.Activities.Add (this.DataCursorActivity25);
            _flow.Loop2.Activities.Add (_flow.Sequence14);
            this.Activities.Add (_flow.Loop2);
            _flow.DataExporterActivity17.Comment = @"";
            _flow.DataExporterActivity17.IconPath = @"";
            VTDPropertyInfoBase pi86 = new VTDPropertyInfoBase("OutTable");
            VTDBaseGetter binding_getter44 = new VTDObjectGetter(pi86);
            VTDPropertyInfoBase pi87 = new VTDPropertyInfoBase("Data");
            VTDBaseSetter binding_setter43 = new VTDObjectSetter(pi87);
            binding_setter43 = new StringFormaterDecorator(binding_setter43,"{Step.DataFetchActivity15.OutTable}");
            bind_dir43 = new BindDirection(_flow.DataFetchActivity15,binding_getter44,binding_setter43,BindTargetType.ToInProperty);
            _flow.DataExporterActivity17.InDirections.Add(bind_dir43);
            this.Activities.Add (_flow.DataExporterActivity17);
            _flow.DataExporterActivity20.Comment = @"";
            _flow.DataExporterActivity20.IconPath = @"";
            VTDPropertyInfoBase pi88 = new VTDPropertyInfoBase("OutTable");
            VTDBaseGetter binding_getter45 = new VTDObjectGetter(pi88);
            VTDPropertyInfoBase pi89 = new VTDPropertyInfoBase("Data");
            VTDBaseSetter binding_setter44 = new VTDObjectSetter(pi89);
            binding_setter44 = new StringFormaterDecorator(binding_setter44,"{Step.DataFetchActivity18.OutTable}");
            bind_dir44 = new BindDirection(_flow.DataFetchActivity18,binding_getter45,binding_setter44,BindTargetType.ToInProperty);
            _flow.DataExporterActivity20.InDirections.Add(bind_dir44);
            this.Activities.Add (_flow.DataExporterActivity20);
            _flow.DataExporterActivity23.Comment = @"";
            _flow.DataExporterActivity23.IconPath = @"";
            VTDPropertyInfoBase pi90 = new VTDPropertyInfoBase("OutTable");
            VTDBaseGetter binding_getter46 = new VTDObjectGetter(pi90);
            VTDPropertyInfoBase pi91 = new VTDPropertyInfoBase("Data");
            VTDBaseSetter binding_setter45 = new VTDObjectSetter(pi91);
            binding_setter45 = new StringFormaterDecorator(binding_setter45,"{Step.DataFetchActivity21.OutTable}");
            bind_dir45 = new BindDirection(_flow.DataFetchActivity21,binding_getter46,binding_setter45,BindTargetType.ToInProperty);
            _flow.DataExporterActivity23.InDirections.Add(bind_dir45);
            this.Activities.Add (_flow.DataExporterActivity23);
            _flow.DataExporterCloseActivity24.Comment = @"";
            _flow.DataExporterCloseActivity24.IconPath = @"";
            this.Activities.Add (_flow.DataExporterCloseActivity24);
            _flow.EndActivity3.Comment = @"";
            _flow.EndActivity3.IconPath = @"AddIns\ServiceTest\BasicActivities\toolbox_code_activity.png";
            _flow.EndActivity3.Name = @"End";
            this.Activities.Add (_flow.EndActivity3);
            _flow.DataDisconnectActivity16.Comment = @"";
            _flow.DataDisconnectActivity16.IconPath = @"";
            VTDPropertyInfoBase pi92 = new VTDPropertyInfoBase("OutTable");
            VTDBaseGetter binding_getter47 = new VTDObjectGetter(pi92);
            VTDPropertyInfoBase pi93 = new VTDPropertyInfoBase("Data");
            VTDBaseSetter binding_setter46 = new VTDObjectSetter(pi93);
            binding_setter46 = new StringFormaterDecorator(binding_setter46,"{Step.DataFetchActivity15.OutTable}");
            bind_dir46 = new BindDirection(_flow.DataFetchActivity15,binding_getter47,binding_setter46,BindTargetType.ToInProperty);
            _flow.DataDisconnectActivity16.InDirections.Add(bind_dir46);
            this.Activities.Add (_flow.DataDisconnectActivity16);
            _flow.DataDisconnectActivity19.Comment = @"";
            _flow.DataDisconnectActivity19.IconPath = @"";
            VTDPropertyInfoBase pi94 = new VTDPropertyInfoBase("OutTable");
            VTDBaseGetter binding_getter48 = new VTDObjectGetter(pi94);
            VTDPropertyInfoBase pi95 = new VTDPropertyInfoBase("Data");
            VTDBaseSetter binding_setter47 = new VTDObjectSetter(pi95);
            binding_setter47 = new StringFormaterDecorator(binding_setter47,"{Step.DataFetchActivity18.OutTable}");
            bind_dir47 = new BindDirection(_flow.DataFetchActivity18,binding_getter48,binding_setter47,BindTargetType.ToInProperty);
            _flow.DataDisconnectActivity19.InDirections.Add(bind_dir47);
            this.Activities.Add (_flow.DataDisconnectActivity19);
            _flow.DataDisconnectActivity22.Comment = @"";
            _flow.DataDisconnectActivity22.IconPath = @"";
            VTDPropertyInfoBase pi96 = new VTDPropertyInfoBase("OutTable");
            VTDBaseGetter binding_getter49 = new VTDObjectGetter(pi96);
            VTDPropertyInfoBase pi97 = new VTDPropertyInfoBase("Data");
            VTDBaseSetter binding_setter48 = new VTDObjectSetter(pi97);
            binding_setter48 = new StringFormaterDecorator(binding_setter48,"{Step.DataFetchActivity21.OutTable}");
            bind_dir48 = new BindDirection(_flow.DataFetchActivity21,binding_getter49,binding_setter48,BindTargetType.ToInProperty);
            _flow.DataDisconnectActivity22.InDirections.Add(bind_dir48);
            this.Activities.Add (_flow.DataDisconnectActivity22);
            this.DataCursorActivity25.Comment = @"";
            this.DataCursorActivity25.IconPath = @"";
            VTDPropertyInfoBase pi98 = new VTDPropertyInfoBase("OutTable");
            VTDBaseGetter binding_getter50 = new VTDObjectGetter(pi98);
            VTDPropertyInfoBase pi99 = new VTDPropertyInfoBase("InTable");
            VTDBaseSetter binding_setter49 = new VTDObjectSetter(pi99);
            binding_setter49 = new StringFormaterDecorator(binding_setter49,"{Step.DataFetchActivity15.OutTable}");
            bind_dir49 = new BindDirection(_flow.DataFetchActivity15,binding_getter50,binding_setter49,BindTargetType.ToInProperty);
            this.DataCursorActivity25.InDirections.Add(bind_dir49);
            this.DataCursorActivity25_Policy.StartPosition = CursorStartPosition.UserSpecificRecord;
            this.DataCursorActivity25_Policy.StartAtSpecificRow = 2;
            this.DataCursorActivity25_Policy.EndPosition = CursorEndPosition.LastRecord;
            this.DataCursorActivity25_Policy.EndAtSpecificRow = 8;
            this.DataCursorActivity25_Policy.StepType = CursorStepType.Forward;
            this.DataCursorActivity25_Policy.StepSize = 1;
            this.DataCursorActivity25_Policy.ActionAfterLastRecord = CursorActionAfterLastRecord.Stay;
            this.DataCursorActivity25.Policy = this.DataCursorActivity25_Policy;
            this.DataCursorActivity25.ReportStepData = true;
            _flow.Loop2.BeforeExecuteStepEvent += this.DataCursorActivity25.ResetCursor;
            _flow.Sequence14.Comment = @"";
            _flow.Sequence14.IconPath = @"";
            _flow.Sequence14.Name = @"Sequence14";
            _flow.Sequence14.Activities.Add (_flow.StServiceCallActivity11);
            _flow.Sequence14.Activities.Add (_flow.StServiceCallActivity13);
            XmlDocument StServiceCallActivity11_InputEnvelope_Document = new XmlDocument();
            StServiceCallActivity11_InputEnvelope_Document.PreserveWhitespace = true;
            StServiceCallActivity11_InputEnvelope_Document.LoadXml(
@"<Envelope xmlns=""http://schemas.xmlsoap.org/soap/envelope/""><Body><GetFlights xmlns=""HP.SOAQ.SampleApp""><DepartureCity>{DataSource.flight_pairing!Input.DepartureCity}</DepartureCity><ArrivalCity>{DataSource.flight_pairing!Input.ArrivalCity}</ArrivalCity><FlightDate>2019-02-28T00:00:00-07:00</FlightDate></GetFlights></Body></Envelope>");
            _flow.StServiceCallActivity11.InputEnvelope = StServiceCallActivity11_InputEnvelope_Document;
            _flow.StServiceCallActivity11.Comment = @"";
            _flow.StServiceCallActivity11.IconPath = @"AddIns\ServiceTest\WSImportTechnology\ictb_service_operations_16.png";
            _flow.StServiceCallActivity11.Name = @"GetFlights";
            _flow.StServiceCallActivity11.TransportProtocol.SOAPProperties.EndpointAddress = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.StServiceCallActivity11.TransportProtocol.SOAPProperties.EndpointAddress}")) ? @"http://localhost:8000/HPFlights_SOAP" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.StServiceCallActivity11.TransportProtocol.SOAPProperties.EndpointAddress}");
            _flow.StServiceCallActivity11.TransportProtocol.SOAPProperties.SoapAction = @"HP.SOAQ.SampleApp/IFlightsSoapService/GetFlights";
            _flow.StServiceCallActivity11.TransportProtocol.SOAPProperties.ContentType = @"text/xml; charset=utf-8";
            _flow.StServiceCallActivity11.TransportProtocol.SOAPProperties.Timeout = (int)100000;
            _flow.StServiceCallActivity11.Service = @"HPFlights_Service";
            _flow.StServiceCallActivity11.Port = @"FlightsServiceMethods";
            _flow.StServiceCallActivity11.Operation = @"GetFlights";
            _flow.StServiceCallActivity11.IsOneWay = false;
            _flow.StServiceCallActivity11.SendRequestToService=true;
            _flow.StServiceCallActivity11.FaultExpected=false;
            _flow.StServiceCallActivity11.IsAsync=false;
            _flow.StServiceCallActivity11.TargetNamespace=@"http://tempuri.org/";
            _flow.StServiceCallActivity11.ListenOnPort = (int)0;
            VTDPropertyInfoBase pi100 = new VTDPropertyInfoBase("DepartureCity");
            VTDBaseGetter binding_getter51 = new VTDObjectGetter(pi100);
            VTDPropertyInfoBase pi101 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlights'][1]/*[local-name(.)='DepartureCity'][1]");
            VTDBaseSetter binding_setter50 = new VTDXPathSetter(pi101,XmlTypeCode.String);
            binding_setter50 = new StringFormaterDecorator(binding_setter50,"{DataSource.flight_pairing!Input.DepartureCity}");
            bind_dir50 = new BindDirection(this.DataCursorActivity25,binding_getter51,binding_setter50,BindTargetType.ToInProperty);
            _flow.StServiceCallActivity11.InDirections.Add(bind_dir50);
            VTDPropertyInfoBase pi102 = new VTDPropertyInfoBase("ArrivalCity");
            VTDBaseGetter binding_getter52 = new VTDObjectGetter(pi102);
            VTDPropertyInfoBase pi103 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlights'][1]/*[local-name(.)='ArrivalCity'][1]");
            VTDBaseSetter binding_setter51 = new VTDXPathSetter(pi103,XmlTypeCode.String);
            binding_setter51 = new StringFormaterDecorator(binding_setter51,"{DataSource.flight_pairing!Input.ArrivalCity}");
            bind_dir51 = new BindDirection(this.DataCursorActivity25,binding_getter52,binding_setter51,BindTargetType.ToInProperty);
            _flow.StServiceCallActivity11.InDirections.Add(bind_dir51);
            XmlDocument StServiceCallActivity11_ExpectedOutputProperties_Document = new XmlDocument();
            StServiceCallActivity11_ExpectedOutputProperties_Document.PreserveWhitespace = true;
            StServiceCallActivity11_ExpectedOutputProperties_Document.LoadXml(
@"<Envelope xmlns=""http://schemas.xmlsoap.org/soap/envelope/"" xmlns:p1=""http://www.w3.org/2001/XMLSchema-instance""><Body><GetFlightsResponse xmlns=""HP.SOAQ.SampleApp""><GetFlightsResult><Flight><Airline p1:nil=""true"" /><ArrivalCity p1:nil=""true"" /><ArrivalTime p1:nil=""true"" /><DepartureCity p1:nil=""true"" /><DepartureTime p1:nil=""true"" /><FlightNumber /></Flight></GetFlightsResult></GetFlightsResponse></Body></Envelope>");
            _flow.StServiceCallActivity11.ExpectedOutputProperties = StServiceCallActivity11_ExpectedOutputProperties_Document;
            XmlDocument StServiceCallActivity11_ExpectedFaultProperties_Document = new XmlDocument();
            StServiceCallActivity11_ExpectedFaultProperties_Document.PreserveWhitespace = true;
            StServiceCallActivity11_ExpectedFaultProperties_Document.LoadXml(
@"<tns:Envelope xmlns:tns=""http://schemas.xmlsoap.org/soap/envelope/""><tns:Body><tns:Fault><faultcode /><faultstring /></tns:Fault></tns:Body></tns:Envelope>");
            _flow.StServiceCallActivity11.ExpectedFaultProperties = StServiceCallActivity11_ExpectedFaultProperties_Document;
            XmlDocument StServiceCallActivity11_ExpectedOutputAttachments_Document = new XmlDocument();
            StServiceCallActivity11_ExpectedOutputAttachments_Document.PreserveWhitespace = true;
            StServiceCallActivity11_ExpectedOutputAttachments_Document.LoadXml(
@"<OutputAttachments />");
            _flow.StServiceCallActivity11.ExpectedOutputAttachments = StServiceCallActivity11_ExpectedOutputAttachments_Document;
            set_StServiceCallActivity11_checkpoints(_flow.StServiceCallActivity11);
            XmlDocument StServiceCallActivity13_InputEnvelope_Document = new XmlDocument();
            StServiceCallActivity13_InputEnvelope_Document.PreserveWhitespace = true;
            StServiceCallActivity13_InputEnvelope_Document.LoadXml(
@"<Envelope xmlns=""http://schemas.xmlsoap.org/soap/envelope/"" xmlns:p1=""http://www.w3.org/2001/XMLSchema-instance""><Body><CreateFlightOrder xmlns=""HP.SOAQ.SampleApp""><FlightOrder><Class>Business</Class><CustomerName>chris</CustomerName><DepartureDate>{Step.InputProperties.StServiceCallActivity11.Body.GetFlights.FlightDate}</DepartureDate><FlightNumber>{Step.OutputProperties.StServiceCallActivity11.Body.GetFlightsResponse.GetFlightsResult.Flight[1].FlightNumber}</FlightNumber><NumberOfTickets>2</NumberOfTickets></FlightOrder></CreateFlightOrder></Body></Envelope>");
            _flow.StServiceCallActivity13.InputEnvelope = StServiceCallActivity13_InputEnvelope_Document;
            _flow.StServiceCallActivity13.Comment = @"";
            _flow.StServiceCallActivity13.IconPath = @"AddIns\ServiceTest\WSImportTechnology\ictb_service_operations_16.png";
            _flow.StServiceCallActivity13.Name = @"CreateFlightOrder";
            _flow.StServiceCallActivity13.TransportProtocol.SOAPProperties.EndpointAddress = String.IsNullOrEmpty(_context.ResourceManager.GetValue(@"{Step.GeneralProperties.StServiceCallActivity13.TransportProtocol.SOAPProperties.EndpointAddress}")) ? @"http://localhost:8000/HPFlights_SOAP" : _context.ResourceManager.GetValue(@"{Step.GeneralProperties.StServiceCallActivity13.TransportProtocol.SOAPProperties.EndpointAddress}");
            _flow.StServiceCallActivity13.TransportProtocol.SOAPProperties.SoapAction = @"HP.SOAQ.SampleApp/IFlightsSoapService/CreateFlightOrder";
            _flow.StServiceCallActivity13.TransportProtocol.SOAPProperties.ContentType = @"text/xml; charset=utf-8";
            _flow.StServiceCallActivity13.TransportProtocol.SOAPProperties.Timeout = (int)100000;
            _flow.StServiceCallActivity13.Service = @"HPFlights_Service";
            _flow.StServiceCallActivity13.Port = @"FlightsServiceMethods";
            _flow.StServiceCallActivity13.Operation = @"CreateFlightOrder";
            _flow.StServiceCallActivity13.IsOneWay = false;
            _flow.StServiceCallActivity13.SendRequestToService=true;
            _flow.StServiceCallActivity13.FaultExpected=false;
            _flow.StServiceCallActivity13.IsAsync=false;
            _flow.StServiceCallActivity13.TargetNamespace=@"http://tempuri.org/";
            _flow.StServiceCallActivity13.ListenOnPort = (int)0;
            VTDPropertyInfoBase pi104 = new VTDPropertyInfoBase("OutputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlightsResponse'][1]/*[local-name(.)='GetFlightsResult'][1]/*[local-name(.)='Flight'][{Array0}]/*[local-name(.)='FlightNumber'][1]");
            VTDBaseGetter binding_getter53 = new VTDXPathGetter(pi104,XmlTypeCode.Int);
            binding_getter53 = new XPathGetterDecorator(binding_getter53,"{Array0}",1);
            VTDPropertyInfoBase pi105 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='CreateFlightOrder'][1]/*[local-name(.)='FlightOrder'][1]/*[local-name(.)='FlightNumber'][1]");
            VTDBaseSetter binding_setter52 = new VTDXPathSetter(pi105,XmlTypeCode.Int);
            bind_dir52 = new BindDirection(_flow.StServiceCallActivity11,binding_getter53,binding_setter52,BindTargetType.ToInProperty);
            _flow.StServiceCallActivity13.InDirections.Add(bind_dir52);
            VTDPropertyInfoBase pi106 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='GetFlights'][1]/*[local-name(.)='FlightDate'][1]");
            VTDBaseGetter binding_getter54 = new VTDXPathGetter(pi106,XmlTypeCode.DateTime);
            VTDPropertyInfoBase pi107 = new VTDPropertyInfoBase("InputEnvelope","/*[local-name(.)='Envelope'][1]/*[local-name(.)='Body'][1]/*[local-name(.)='CreateFlightOrder'][1]/*[local-name(.)='FlightOrder'][1]/*[local-name(.)='DepartureDate'][1]");
            VTDBaseSetter binding_setter53 = new VTDXPathSetter(pi107,XmlTypeCode.DateTime);
            bind_dir53 = new BindDirection(_flow.StServiceCallActivity11,binding_getter54,binding_setter53,BindTargetType.ToInProperty);
            _flow.StServiceCallActivity13.InDirections.Add(bind_dir53);
            XmlDocument StServiceCallActivity13_ExpectedOutputProperties_Document = new XmlDocument();
            StServiceCallActivity13_ExpectedOutputProperties_Document.PreserveWhitespace = true;
            StServiceCallActivity13_ExpectedOutputProperties_Document.LoadXml(
@"<Envelope xmlns=""http://schemas.xmlsoap.org/soap/envelope/""><Body><CreateFlightOrderResponse xmlns=""HP.SOAQ.SampleApp""><CreateFlightOrderResult><OrderNumber>90</OrderNumber><TotalPrice>640</TotalPrice></CreateFlightOrderResult></CreateFlightOrderResponse></Body></Envelope>");
            _flow.StServiceCallActivity13.ExpectedOutputProperties = StServiceCallActivity13_ExpectedOutputProperties_Document;
            XmlDocument StServiceCallActivity13_ExpectedFaultProperties_Document = new XmlDocument();
            StServiceCallActivity13_ExpectedFaultProperties_Document.PreserveWhitespace = true;
            StServiceCallActivity13_ExpectedFaultProperties_Document.LoadXml(
@"<tns:Envelope xmlns:tns=""http://schemas.xmlsoap.org/soap/envelope/""><tns:Body><tns:Fault><faultcode /><faultstring /></tns:Fault></tns:Body></tns:Envelope>");
            _flow.StServiceCallActivity13.ExpectedFaultProperties = StServiceCallActivity13_ExpectedFaultProperties_Document;
            XmlDocument StServiceCallActivity13_ExpectedOutputAttachments_Document = new XmlDocument();
            StServiceCallActivity13_ExpectedOutputAttachments_Document.PreserveWhitespace = true;
            StServiceCallActivity13_ExpectedOutputAttachments_Document.LoadXml(
@"<OutputAttachments />");
            _flow.StServiceCallActivity13.ExpectedOutputAttachments = StServiceCallActivity13_ExpectedOutputAttachments_Document;
            set_StServiceCallActivity13_checkpoints(_flow.StServiceCallActivity13);
            
        }
        
        internal void InitializeEncryptionManagerValues()
        {
        
        }
        	
    	bool useReport = true;
    
    	protected override STExecutionResult ExecuteStep()
        {
            return base.ExecuteStep();
        }
    
        public void Start()
        {
    	    try
    		{
    		  Workflow_Executing();
    		  this.ExecuteStep();
    		}
    		finally
    		{
    		  WorkFlowScript_Completed();
    		}
        }
    
    	private void InitReport()
    	{
    		if (useReport)
    		{	
    			// Intialize Reporter
    			string reportDBDir = Path.Combine(this._context.ReportDirectory, @"Report");
    			CleanupReport(reportDBDir);        	
    			string reportDBPath = Path.Combine(reportDBDir, "VTDReport.mdb");        	
    			if (reporter == null)
    			{
    				reporter = new Reporter(reportDBPath);
    			}
    			_context.Reporter = reporter;
    		}
    	}
    
        public static void CopyDirectory(string Src, string Dst)
        {
            String[] Files;
    
            if (Dst[Dst.Length - 1] != Path.DirectorySeparatorChar)
                Dst += Path.DirectorySeparatorChar;
            if (!Directory.Exists(Dst)) Directory.CreateDirectory(Dst);
            Files = Directory.GetFileSystemEntries(Src);
            foreach (string Element in Files)
            {
                // Sub directories
                if (Directory.Exists(Element))
                    CopyDirectory(Element, Dst + Path.GetFileName(Element));
                // Files in directory
                else
                    File.Copy(Element, Dst + Path.GetFileName(Element), true);
            }
        }
        
        private void CleanupReport(string reportDBDir)
        {   
    		if (useReport)
    		{             
    			string reportTemplateDir = Path.Combine(ServiceTestRunner.GetInstallPath(),@"bin\ReportResources");                
    			try
    			{
            		CopyDirectory(reportTemplateDir, reportDBDir);
    			}
    			catch //(Exception ex)
    			{
    				//ToDo: LoggingService.Warn("Report Cleanup Error", ex);
    			}
    		}
        }
    
        void Workflow_Executing()
        {   
        	InitReportNode();
                       
        }
    
    	private void InitReportNode()
    	{
    		if (useReport)
    		{	
        		// Init report creator
    			this.reportCreator = new HP.ST.Fwk.ReportCreator.QTPEngine.QTPEngineReportCreator();
    			this.reportLevelInTree = reportCreator.Init(_context.EnvironmentProfile.GetVariableValue("TestName"), _context);
                
    			STActivityBase activity = this;
    			string workflowID = activity.GetHashCode().ToString();
    			ReportNodeCreationData newNodeData =
    			new ReportNodeCreationData(workflowID, workflowID, DateTime.Now);
    			reporter.CreateReportNode(newNodeData);
            
    			ReportInfoData newReportData = new ReportInfoData(workflowID, ReportKeywords.TypeKeywordTag, this.GetType().ToString());
    			reporter.SendReportData(newReportData);
    			newReportData = new ReportInfoData(workflowID, ReportKeywords.NameKeywordTag, this.Name);
    			//TrackData(ReportInfoData.InfoDataTag, newReportData);
    			reporter.SendReportData(newReportData);            
            }
    	}
        
        void WorkFlowScript_Completed()
        {   
    		
    
    		CreateReportFiles();
    					
        	// Write all snapshots to disk
    		this._context.SnapshotManager.WriteSnapshotsToDisk();
    
    		OnExecutionCompleted();
    		
        }
    
    	private void CreateReportFiles()
    	{
    		if (useReport)
    		{	
    			//Dispose reporter inorder to close connection to report DB
           		this._context.Reporter.Dispose();
            	
           		// Run report creator
    			reportCreator.RunOnDBAndCreateFiles();
    		}
    	}
    
        
        void Workflow_Faulting()
        {
    		
    
    		CreateReportFiles();
            // Write all snapshots to disk
    		this._context.SnapshotManager.WriteSnapshotsToDisk();
           
    		OnExecutionCompleted();
        }
    
    	protected override QcSystemVariables GetRuntimeQcVariables(ISTRunTimeContext context)
    	{
    		return new HP.ST.Ext.BasicActivities.RuntimeQcVariables(this._context);
    	}
            
    	protected override TestSystemVariables GetTestSystemVariables(ISTRunTimeContext context)
    	{
    		return new HP.ST.Ext.BasicActivities.RuntimeTestVariables(this._context);
    	}
    
    	private void UpdateTestSettings(ISTRunTimeContext ctx)
        {
    		ctx.PropertyBag["StopTestOnStepFailure"] = true;
    	}
    }
    
    public partial class VuserClass
    {
    	public static string[] CommandLineArguments;
    	public static string[] DotNetResolverPaths;
    	
        public VuserClass()
        {
    				
    		AssemblyResolver.AddSTPathsToResolutionPaths();
    		AssemblyResolver.AttachToAppdomain();
        }
    
        private void AddAssemblyResolver()
        {
    		AssemblyResolver.AddTestPathToResolutionPaths(GetTestPath());
    		AssemblyResolver.AddPathsForAssemblyResolution(DotNetResolverPaths);
        }
    	
        public int STAction()
        {	
            AddAssemblyResolver();
            STRunTimeContext ctx = new STRunTimeContext(Directory.GetParent(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)).FullName, string.Empty);
            WorkFlowScript script = new WorkFlowScript(ctx);
            script.InitializeComponent();
            script.Start();       
            
            return 0;
        }
        
        public void NotifyLicenseException(string msg)
        {
        		
    		try
    		{
    		    STRunTimeContext ctx = new STRunTimeContext(Directory.GetParent(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)).FullName, string.Empty);
                WorkFlowScript script = new WorkFlowScript(ctx);
                script.InitializeComponent();
                script.Context.ReplayClient.OnLicenseFailure(msg);
                
            }
            catch (Exception)
            {
    			// ToDo: log the error message
            }        
        }
    
    	 protected string GetTestPath()
            {
                if (CommandLineArguments != null)
                {
                    for (int i = 0; i < CommandLineArguments.Length; i++)
                    {
                        if (CommandLineArguments[i].Equals("-test", StringComparison.OrdinalIgnoreCase))
                        {
                            return CommandLineArguments[i + 1];
                        }
                    }
                }
                return String.Empty;
            }
        
    }
    
    }
    